export const authMessages = {
  welcomeBack: 'Welcome Back!',
  welcomeNew: 'Welcome!',
  loginFailed: 'Login failed',
  registrationFailed: 'Registration failed',
  loginError: 'An error occurred during login',
  registrationError: 'An error occurred during registration',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  emailPlaceholder: 'name@example.com',
  passwordPlaceholder: '********',
  signingUp: 'Signing up...',
  loggingIn: 'Logging in...',
  signUp: 'Sign Up',
  logIn: 'Log In',
  haveAccount: 'Already have an account?',
  noAccount: "Don't have an account?",
  forgotPassword: 'Forgot your password?',
  getStarted: 'Get Started',
};
